export const dateListTypes = {
  UPDATE_DATELIST: "UPDATE_DATELIST",
  DELETE_DATE: "DELETE_DATELIST",
  DELETE_DATE_FB: "DELETE_DATELIST_FB",
  INSERT_DATE: "INSERT_DATELIST",
  INSERT_DATE_FB: "INSERT_DATELIST_FB",
};
