export const dateListTypes = {
  GET_DATELIST: "GET_DATELIST",
  GET_DATELIST_FB: "GET_DATELIST_FB",
  DELETE_DATELIST: "DELETE_DATELIST",
  DELETE_DATELIST_FB: "DELETE_DATELIST_FB",
  INSERT_DATELIST: "INSERT_DATELIST",
  INSERT_DATELIST_FB: "INSERT_DATELIST_FB",
};
